### ISSUE TITLE
APScheduler usage produces excessive noise on logs

### ISSUE THREAD

**Issue by tiagojsag** [gfw-api/glad-analysis-tiled#15]
Hi,

Seems that the latest changes in the develop branch produce a lot of noise on the "error" channel of the logs, on things that don't really seem to be errors:

https://console.cloud.google.com/logs/viewer?time=P1D&project=resource-watch&authuser=1&minLogLevel=400&expandAll=false&timestamp=2019-03-25T07:52:27.448000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-03-25T06:52:27.699Z&dateRangeEnd=2019-03-25T07:52:27.699Z&interval=PT1H&resource=container%2Fcluster_name%2Fwri-staging&scrollTimestamp=2019-03-25T07:17:02.000000000Z&logName=projects%2Fresource-watch%2Flogs%2Fglad-analysis-athena

This is functionally harmless, but it produces a lot of noise on GCP, which we use to identify and fix issues. While it's not urgent to fix, we do want to avoid a "broken window" effect with this, so this should be fixed whenever we have a moment.

**Comment by thomas-maschler** [comment]
should be addressed here #16
